// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrE9H-3NphjAuUNU4Oc7hgpHe5dyqk71k',
    appId: '1:908596289904:web:5169c72c833f49564befb5',
    messagingSenderId: '908596289904',
    projectId: 'medtrack-f2c5d',
    authDomain: 'medtrack-f2c5d.firebaseapp.com',
    storageBucket: 'medtrack-f2c5d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8tmCC497dLuzsU6d2h1RJBz7nD5U1Fdo',
    appId: '1:908596289904:android:ed5befe5a005e2a54befb5',
    messagingSenderId: '908596289904',
    projectId: 'medtrack-f2c5d',
    storageBucket: 'medtrack-f2c5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACNFF2v7AwH7XSZZELLNa2P81hk65DP08',
    appId: '1:908596289904:ios:1052d885d1ed0cbc4befb5',
    messagingSenderId: '908596289904',
    projectId: 'medtrack-f2c5d',
    storageBucket: 'medtrack-f2c5d.firebasestorage.app',
    iosBundleId: 'com.example.medtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACNFF2v7AwH7XSZZELLNa2P81hk65DP08',
    appId: '1:908596289904:ios:1052d885d1ed0cbc4befb5',
    messagingSenderId: '908596289904',
    projectId: 'medtrack-f2c5d',
    storageBucket: 'medtrack-f2c5d.firebasestorage.app',
    iosBundleId: 'com.example.medtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrE9H-3NphjAuUNU4Oc7hgpHe5dyqk71k',
    appId: '1:908596289904:web:6a83034931ff1ab34befb5',
    messagingSenderId: '908596289904',
    projectId: 'medtrack-f2c5d',
    authDomain: 'medtrack-f2c5d.firebaseapp.com',
    storageBucket: 'medtrack-f2c5d.firebasestorage.app',
  );
}
